### ISSUE TITLE
What are the right measurement units for accelerometer and magnetometer data?

### ISSUE THREAD

**Issue by mohataher** [morgil/madgwick_py#1]
What's the right measurement units for accelerometer and magnetometer data? It's mentioned that gyroscope data should be in radians per seconds. How about others?

An example would be great. Thanks for the repo.

**Comment by morgil** [comment]
The accelerometer and magnetometer units do not matter, as they will be normalized to 1. I have added this to the docstring, thank you for the suggestion.
